grails-app/domain/com/vallenova/restaurante/modelo/Receta.groovy
package com.vallenova.restaurante.modelo

class Receta {

	String nombre
	
	String toString() {
		nombre
	}
	static hasMany = [ingredientes:Ingrediente]
	
    static constraints = {
		nombre blank:false, size:2..160
    }
}

grails-app/controllers/com/vallenova/restaurante/modelo/IngredienteController.groovy
package com.vallenova.restaurante.modelo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class IngredienteController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Ingrediente.list(params), model:[ingredienteInstanceCount: Ingrediente.count()]
    }

    def show(Ingrediente ingredienteInstance) {
        respond ingredienteInstance
    }

    def create() {
        respond new Ingrediente(params)
    }

    @Transactional
    def save(Ingrediente ingredienteInstance) {
        if (ingredienteInstance == null) {
            notFound()
            return
        }

        if (ingredienteInstance.hasErrors()) {
            respond ingredienteInstance.errors, view:'create'
            return
        }

        ingredienteInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'ingredienteInstance.label', default: 'Ingrediente'), ingredienteInstance.id])
                redirect ingredienteInstance
            }
            '*' { respond ingredienteInstance, [status: CREATED] }
        }
    }

    def edit(Ingrediente ingredienteInstance) {
        respond ingredienteInstance
    }

    @Transactional
    def update(Ingrediente ingredienteInstance) {
        if (ingredienteInstance == null) {
            notFound()
            return
        }

        if (ingredienteInstance.hasErrors()) {
            respond ingredienteInstance.errors, view:'edit'
            return
        }

        ingredienteInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Ingrediente.label', default: 'Ingrediente'), ingredienteInstance.id])
                redirect ingredienteInstance
            }
            '*'{ respond ingredienteInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Ingrediente ingredienteInstance) {

        if (ingredienteInstance == null) {
            notFound()
            return
        }

        ingredienteInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Ingrediente.label', default: 'Ingrediente'), ingredienteInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'ingredienteInstance.label', default: 'Ingrediente'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/vallenova/restaurante/modelo/RecetaController.groovy
package com.vallenova.restaurante.modelo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RecetaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Receta.list(params), model:[recetaInstanceCount: Receta.count()]
    }

    def show(Receta recetaInstance) {
        respond recetaInstance
    }

    def create() {
        respond new Receta(params)
    }

    @Transactional
    def save(Receta recetaInstance) {
        if (recetaInstance == null) {
            notFound()
            return
        }

        if (recetaInstance.hasErrors()) {
            respond recetaInstance.errors, view:'create'
            return
        }

        recetaInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'recetaInstance.label', default: 'Receta'), recetaInstance.id])
                redirect recetaInstance
            }
            '*' { respond recetaInstance, [status: CREATED] }
        }
    }

    def edit(Receta recetaInstance) {
        respond recetaInstance
    }

    @Transactional
    def update(Receta recetaInstance) {
        if (recetaInstance == null) {
            notFound()
            return
        }

        if (recetaInstance.hasErrors()) {
            respond recetaInstance.errors, view:'edit'
            return
        }

        recetaInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Receta.label', default: 'Receta'), recetaInstance.id])
                redirect recetaInstance
            }
            '*'{ respond recetaInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Receta recetaInstance) {

        if (recetaInstance == null) {
            notFound()
            return
        }

        recetaInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Receta.label', default: 'Receta'), recetaInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'recetaInstance.label', default: 'Receta'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/receta/_form.gsp
<%@ page import="com.vallenova.restaurante.modelo.Receta" %>



<div class="fieldcontain ${hasErrors(bean: recetaInstance, field: 'nombre', 'error')} required">
	<label for="nombre">
		<g:message code="receta.nombre.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombre" maxlength="160" required="" value="${recetaInstance?.nombre}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: recetaInstance, field: 'ingredientes', 'error')} ">
	<label for="ingredientes">
		<g:message code="receta.ingredientes.label" default="Ingredientes" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${recetaInstance?.ingredientes?}" var="i">
    <li><g:link controller="ingrediente" action="show" id="${i.id}">${i?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="ingrediente" action="create" params="['receta.id': recetaInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'ingrediente.label', default: 'Ingrediente')])}</g:link>
</li>
</ul>

</div>

grails-app/views/receta/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'receta.label', default: 'Receta')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-receta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-receta" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${recetaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${recetaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:recetaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/receta/edit.gsp
<%@ page import="com.vallenova.restaurante.modelo.Receta" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'receta.label', default: 'Receta')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-receta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-receta" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${recetaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${recetaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:recetaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${recetaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/receta/index.gsp
<%@ page import="com.vallenova.restaurante.modelo.Receta" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'receta.label', default: 'Receta')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-receta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-receta" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nombre" title="${message(code: 'receta.nombre.label', default: 'Nombre')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${recetaInstanceList}" status="i" var="recetaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${recetaInstance.id}">${fieldValue(bean: recetaInstance, field: "nombre")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${recetaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/receta/show.gsp
<%@ page import="com.vallenova.restaurante.modelo.Receta" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'receta.label', default: 'Receta')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-receta" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-receta" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list receta">
			
				<g:if test="${recetaInstance?.nombre}">
				<li class="fieldcontain">
					<span id="nombre-label" class="property-label"><g:message code="receta.nombre.label" default="Nombre" /></span>
					
						<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${recetaInstance}" field="nombre"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${recetaInstance?.ingredientes}">
				<li class="fieldcontain">
					<span id="ingredientes-label" class="property-label"><g:message code="receta.ingredientes.label" default="Ingredientes" /></span>
					
						<g:each in="${recetaInstance.ingredientes}" var="i">
						<span class="property-value" aria-labelledby="ingredientes-label"><g:link controller="ingrediente" action="show" id="${i.id}">${i?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:recetaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${recetaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>