grails-app/domain/com/vallenova/restaurante/modelo/Ingrediente.groovy
package com.vallenova.restaurante.modelo

class Ingrediente {

	static belongsTo = [insumo:Insumo, receta:Receta]
	BigDecimal cantidad
    
	String toString() {
		insumo
	}
	
	static constraints = {
    }
}

grails-app/controllers/com/vallenova/restaurante/modelo/IngredienteController.groovy
package com.vallenova.restaurante.modelo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class IngredienteController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Ingrediente.list(params), model:[ingredienteInstanceCount: Ingrediente.count()]
    }

    def show(Ingrediente ingredienteInstance) {
        respond ingredienteInstance
    }

    def create() {
        respond new Ingrediente(params)
    }

    @Transactional
    def save(Ingrediente ingredienteInstance) {
        if (ingredienteInstance == null) {
            notFound()
            return
        }

        if (ingredienteInstance.hasErrors()) {
            respond ingredienteInstance.errors, view:'create'
            return
        }

        ingredienteInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'ingredienteInstance.label', default: 'Ingrediente'), ingredienteInstance.id])
                redirect ingredienteInstance
            }
            '*' { respond ingredienteInstance, [status: CREATED] }
        }
    }

    def edit(Ingrediente ingredienteInstance) {
        respond ingredienteInstance
    }

    @Transactional
    def update(Ingrediente ingredienteInstance) {
        if (ingredienteInstance == null) {
            notFound()
            return
        }

        if (ingredienteInstance.hasErrors()) {
            respond ingredienteInstance.errors, view:'edit'
            return
        }

        ingredienteInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Ingrediente.label', default: 'Ingrediente'), ingredienteInstance.id])
                redirect ingredienteInstance
            }
            '*'{ respond ingredienteInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Ingrediente ingredienteInstance) {

        if (ingredienteInstance == null) {
            notFound()
            return
        }

        ingredienteInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Ingrediente.label', default: 'Ingrediente'), ingredienteInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'ingredienteInstance.label', default: 'Ingrediente'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/ingrediente/_form.gsp
<%@ page import="com.vallenova.restaurante.modelo.Ingrediente" %>



<div class="fieldcontain ${hasErrors(bean: ingredienteInstance, field: 'cantidad', 'error')} required">
	<label for="cantidad">
		<g:message code="ingrediente.cantidad.label" default="Cantidad" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="cantidad" value="${fieldValue(bean: ingredienteInstance, field: 'cantidad')}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: ingredienteInstance, field: 'insumo', 'error')} required">
	<label for="insumo">
		<g:message code="ingrediente.insumo.label" default="Insumo" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="insumo" name="insumo.id" from="${com.vallenova.restaurante.modelo.Insumo.list()}" optionKey="id" required="" value="${ingredienteInstance?.insumo?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: ingredienteInstance, field: 'receta', 'error')} required">
	<label for="receta">
		<g:message code="ingrediente.receta.label" default="Receta" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="receta" name="receta.id" from="${com.vallenova.restaurante.modelo.Receta.list()}" optionKey="id" required="" value="${ingredienteInstance?.receta?.id}" class="many-to-one"/>
</div>

grails-app/views/ingrediente/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ingrediente.label', default: 'Ingrediente')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-ingrediente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-ingrediente" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${ingredienteInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${ingredienteInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:ingredienteInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/ingrediente/edit.gsp
<%@ page import="com.vallenova.restaurante.modelo.Ingrediente" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ingrediente.label', default: 'Ingrediente')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-ingrediente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-ingrediente" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${ingredienteInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${ingredienteInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:ingredienteInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${ingredienteInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/ingrediente/index.gsp
<%@ page import="com.vallenova.restaurante.modelo.Ingrediente" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ingrediente.label', default: 'Ingrediente')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-ingrediente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-ingrediente" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="cantidad" title="${message(code: 'ingrediente.cantidad.label', default: 'Cantidad')}" />
					
						<th><g:message code="ingrediente.insumo.label" default="Insumo" /></th>
					
						<th><g:message code="ingrediente.receta.label" default="Receta" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${ingredienteInstanceList}" status="i" var="ingredienteInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${ingredienteInstance.id}">${fieldValue(bean: ingredienteInstance, field: "cantidad")}</g:link></td>
					
						<td>${fieldValue(bean: ingredienteInstance, field: "insumo")}</td>
					
						<td>${fieldValue(bean: ingredienteInstance, field: "receta")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${ingredienteInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/ingrediente/show.gsp
<%@ page import="com.vallenova.restaurante.modelo.Ingrediente" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'ingrediente.label', default: 'Ingrediente')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-ingrediente" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-ingrediente" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list ingrediente">
			
				<g:if test="${ingredienteInstance?.cantidad}">
				<li class="fieldcontain">
					<span id="cantidad-label" class="property-label"><g:message code="ingrediente.cantidad.label" default="Cantidad" /></span>
					
						<span class="property-value" aria-labelledby="cantidad-label"><g:fieldValue bean="${ingredienteInstance}" field="cantidad"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${ingredienteInstance?.insumo}">
				<li class="fieldcontain">
					<span id="insumo-label" class="property-label"><g:message code="ingrediente.insumo.label" default="Insumo" /></span>
					
						<span class="property-value" aria-labelledby="insumo-label"><g:link controller="insumo" action="show" id="${ingredienteInstance?.insumo?.id}">${ingredienteInstance?.insumo?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${ingredienteInstance?.receta}">
				<li class="fieldcontain">
					<span id="receta-label" class="property-label"><g:message code="ingrediente.receta.label" default="Receta" /></span>
					
						<span class="property-value" aria-labelledby="receta-label"><g:link controller="receta" action="show" id="${ingredienteInstance?.receta?.id}">${ingredienteInstance?.receta?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:ingredienteInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${ingredienteInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>